name = input("\nEnter Your full name: ") 
print("") 
print(name) 
print(f"No. of characters: {len(name)}") 
print(f"First Letter: {name[0]}") 
print(f"Last Letter: {name[-1]}") 
print(f"Uppercase: {name.upper()}") 
print(f"Lowercase: {name.lower()}")  
print(f"Initials: {name[0:2]}") 
